### ISSUE TITLE
Windows Build - Error parsing IFC File

### ISSUE THREAD

**Issue by Spirit30** [helpsterTee/Unity-IFCEngine#2]
Hi, Thanks for the Great Work

Can you help with Error parsing IFC File on Windows platform?
It works fine in the Editor.
Fixed a couple of small issues during the build.
But this one is related to dll which is closed for editiong.

I've tried both builds 86_64, 86.
And Dot .Net 2.0 instead of Subset.
Any Ideas?

Bellow you can see full log from the app which is pretty obvious.

Thank you very much!

Initialize engine version: 2017.2.0f3 (46dda1414e51)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GT 740M (ID=0x1292)
    Vendor:   NVIDIA
    VRAM:     2020 MB
    Driver:   21.21.13.7654
Begin MonoManager ReloadAssembly
- Completed reload, in  0.042 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

Setting up 4 worker threads for Enlighten.
  Thread -> id: 31c0 -> priority: 1 
  Thread -> id: 27cc -> priority: 1 
  Thread -> id: 1b00 -> priority: 1 
  Thread -> id: fe0 -> priority: 1 
UnloadTime: 4.306400 ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

F:\USER\Desktop\Win_EXE\IFC_Test\IfcOpenHouseGeoRef.ifc
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Parsing geometry from IFC file
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Error parsing IFC File
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

IfcOpenHouseGeoRef is Imported!
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by helpsterTee** [comment]
That actually looks like a path problem to me. Can you supply a screenshot with your folder structure in the Win_EXE directory?

**Comment by Spirit30** [comment]
Thanks for Ideas!

Here are screenshots:
![win_exe 2018-07-19 12 59 23](https://user-images.githubusercontent.com/9005398/42935992-a83dda1c-8b53-11e8-9194-2ad9bbfee84f.png)
![ifc_test 2018-07-19 13 02 44](https://user-images.githubusercontent.com/9005398/42936179-1a754584-8b54-11e8-8d25-13330e514035.png)
![ifc_data 2018-07-19 13 03 52](https://user-images.githubusercontent.com/9005398/42936303-6c493618-8b54-11e8-83c2-47783a7967c4.png)
![plugins 2018-07-19 13 04 08](https://user-images.githubusercontent.com/9005398/42936325-74db5996-8b54-11e8-9587-4659e6128677.png)
![managed 2018-07-19 13 04 33](https://user-images.githubusercontent.com/9005398/42936352-818fabe2-8b54-11e8-94e0-8d4c60902f23.png)

Bellow is changed version of Manager.cs
It reads .ifc file from the Root (of Unity project if Editor or where windows build .exe is located).
It is done because .ifc file included into Assets was existed as binary part of builded Unity resources.
Correct me if I'm wrong.
Looking forward for your feedback.

Thank you!

using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class Manager : MonoBehaviour {

    public string fileName = "IfcOpenHouseGeoRef";
    ImportIFC import;

	void Start () {

        string fileFormat = Path.Combine(Directory.GetCurrentDirectory(), "{0}.ifc");
        string filePath = Path.GetFullPath(string.Format(fileFormat, fileName));
        Debug.Log(filePath);
        Debug.Log(File.ReadAllText(filePath));
        import = GetComponentInChildren<ImportIFC>();
        import.ImportFinished += new ImportIFC.CallbackEventHandler(ImportIsFinished);
        import.Init();
        import.ImportFile(filePath, fileName);
	}

    public void ImportIsFinished(GameObject go)
    {
        Debug.Log(go.name + " is Imported!");
    }
}

**Comment by helpsterTee** [comment]
Did you copy the IFC2X3-Settings.xml and IFC4-Settings.xml into the binary directory? This is needed for reading the IFC files.

**Comment by Spirit30** [comment]
This did the trick.
Thanks Man!

Great job,
Regards Spirit

**Comment by helpsterTee** [comment]
>This did the trick. ...

@Spirit30 it's great people try to use it ;) if you build something presentable, just drop a note :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
