### ISSUE TITLE
Make compatible for release build

### ISSUE THREAD

**Issue by helpsterTee** [helpsterTee/Unity-IFCEngine#9]
Build is currently crashing when releasing or not loading the IFC file at all.

**Comment by helpsterTee** [comment]
Needed for #6

**Comment by helpsterTee** [comment]
Prefab generation not available in release builds. This is not a problem, because we only need the prefab when placing stuff in the editor. Mitigate by using preprocessor directives.

**Comment by helpsterTee** [comment]
Need to add build scripts to copy necessary IFC define XMLs and the example IFC file to output directory

**Comment by helpsterTee** [comment]
Runtime crashing while loading IFC file with:

`0x00007FFF6398C059 (ifcengine) GetSPFFHeaderItem
0x0000016170417912 (Mono JIT Code) (wrapper managed-to-native) IfcEngine.x86_64:GetSPFFHeaderItem (int,int,int,int,intptr&)
0x0000016170416706 (Mono JIT Code) IfcEngineWrapper.IfcUtil:ParseIFCFile (string)
0x00000161703DC3F1 (Mono JIT Code) [Unity-IFCEngine-Project\Assets\IFCImporter\ScIFC\ImportIFC.cs:106] ImportIFC/<Import>c__Iterator0:MoveNext () 
0x00000161703D85A9 (Mono JIT Code) [Unity-IFCEngine-Project\Assets\CielaSpike\Thread Ninja\Task.cs:242] CielaSpike.Task:MoveNextUnity () 
0x00000161703D838F (Mono JIT Code) [Unity-IFCEngine-Project\Assets\CielaSpike\Thread Ninja\Task.cs:233] CielaSpike.Task:BackgroundRunner (object) 
0x00000161703A025D (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
0x00007FFF66B1671B (mono) mono_set_defaults
0x00007FFF66A68A71 (mono) mono_runtime_invoke
0x00007FFF66A6EF87 (mono) mono_runtime_invoke_array
0x00007FFF66A6F25C (mono) mono_runtime_invoke_array
0x00007FFF66A8F8F3 (mono) mono_security_set_mode
0x00007FFF66A9034A (mono) mono_security_set_mode
0x00007FFF66A94097 (mono) mono_thread_interruption_request_flag
0x00007FFF66B4A117 (mono) mono_unity_install_unitytls_interface
0x00007FFFA74C3DC4 (KERNEL32) BaseThreadInitThunk
0x00007FFFA7F93691 (ntdll) RtlUserThreadStart`

**Comment by eswarborra** [comment]
Hi,
Did you get any update..?

**Comment by helpsterTee** [comment]
I was able to just build with x86 only. There seems to be a problem with x86_64. I have to look into this, but at least this will work. I guess there is some confusion in data types in the unmanaged dll.

**Comment by helpsterTee** [comment]
@eswarborra can you try building with the latest master and x86 target?

**Comment by eswarborra** [comment]
> @eswarborra can you try building with the latest master and x86 target?

Yes i will.. I Made a build in x86 (UWP) build was success, but after deploying the build it's not showing anything on device..After switching UWP it's working on Editor but not in Device..

**Comment by helpsterTee** [comment]
Did you put your IFC files to the main app directory? It's a workaround for now, but it will load the files from the project root dir, if not in Editor mode. I don't know how this is handled on the Hololens.

**Comment by helpsterTee** [comment]
Closed due to inactivity

**Comment by felixwcf** [comment]
Hi I'm facing the same issue, running on MacOS. Need it on x86_64. Thank you.
